openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/auth/register:
    post:
      summary: ''
      operationId: postApiAuthRegister
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                  description: 'Must not be greater than 100 characters.'
                  example: pulgbcrvm
                middle_name:
                  type: string
                  description: 'Must not be greater than 100 characters.'
                  example: vbonfbwvvvciea
                last_name:
                  type: string
                  description: 'Must not be greater than 100 characters.'
                  example: izjenlqgsitkncvcffwr
                email:
                  type: string
                  description: 'Must be a valid email address. Must not be greater than 255 characters.'
                  example: swalsh@example.org
                password:
                  type: string
                  description: 'Must be at least 8 characters. Must not be greater than 64 characters.'
                  example: 'PLXlVsZ^;c{uw"/^'
                picture:
                  type: string
                  format: binary
                  description: 'Must be an image. Must not be greater than 2048 kilobytes.'
              required:
                - first_name
                - middle_name
                - last_name
                - email
                - password
      security: []
  /api/auth/login:
    post:
      summary: ''
      operationId: postApiAuthLogin
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: ''
                  example: connelly.carmela@example.org
                password:
                  type: string
                  description: ''
                  example: '%fqHnCT?y~jp'
              required:
                - email
                - password
      security: []
  /api/auth/logout:
    post:
      summary: ''
      operationId: postApiAuthLogout
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
  /api/vendor/register:
    post:
      summary: ''
      operationId: postApiVendorRegister
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                store_name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: mjtpscwkmjiwvubheozp
                phone_number:
                  type: string
                  description: 'Must not be greater than 15 characters.'
                  example: goneueyfsferrvq
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: gerlach.darby@example.net
                logo:
                  type: string
                  format: binary
                  description: 'Must be an image. Must not be greater than 2048 kilobytes.'
                zone:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: wxfn
                region:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: irmcuyohrkvrs
                google_map_location:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: romgywloh
                website:
                  type: string
                  description: 'Must be a valid URL. Must not be greater than 255 characters.'
                  example: gemjjkzxeg
                telegram:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: dwcczghucebgxfujabqo
                whatsapp:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: moxvihpccdtihgjdwrlys
                tin_number:
                  type: string
                  description: 'Must be 10 characters.'
                  example: vzzfgylueh
                license:
                  type: string
                  format: binary
                  description: 'Must be a file. Must not be greater than 2048 kilobytes.'
                description:
                  type: string
                  description: 'Must not be greater than 1000 characters.'
                  example: 'Sed dolorem ipsum quia non modi.'
              required:
                - store_name
                - phone_number
                - email
                - zone
                - region
                - tin_number
                - license
  /api/vendor/list:
    get:
      summary: ''
      operationId: getApiVendorList
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  current_page: 39
                  data: []
                  first_page_url: 'http://localhost/api/vendor/list?page=1'
                  from: null
                  last_page: 1
                  last_page_url: 'http://localhost/api/vendor/list?page=1'
                  links:
                    -
                      url: 'http://localhost/api/vendor/list?page=38'
                      label: '&laquo; Previous'
                      active: false
                    -
                      url: 'http://localhost/api/vendor/list?page=1'
                      label: '1'
                      active: false
                    -
                      url: null
                      label: 'Next &raquo;'
                      active: false
                  next_page_url: null
                  path: 'http://localhost/api/vendor/list'
                  per_page: 40
                  prev_page_url: 'http://localhost/api/vendor/list?page=38'
                  to: null
                  total: 0
                properties:
                  current_page:
                    type: integer
                    example: 39
                  data:
                    type: array
                    example: []
                  first_page_url:
                    type: string
                    example: 'http://localhost/api/vendor/list?page=1'
                  from:
                    type: string
                    example: null
                  last_page:
                    type: integer
                    example: 1
                  last_page_url:
                    type: string
                    example: 'http://localhost/api/vendor/list?page=1'
                  links:
                    type: array
                    example:
                      -
                        url: 'http://localhost/api/vendor/list?page=38'
                        label: '&laquo; Previous'
                        active: false
                      -
                        url: 'http://localhost/api/vendor/list?page=1'
                        label: '1'
                        active: false
                      -
                        url: null
                        label: 'Next &raquo;'
                        active: false
                    items:
                      type: object
                      properties:
                        url:
                          type: string
                          example: 'http://localhost/api/vendor/list?page=38'
                        label:
                          type: string
                          example: '&laquo; Previous'
                        active:
                          type: boolean
                          example: false
                  next_page_url:
                    type: string
                    example: null
                  path:
                    type: string
                    example: 'http://localhost/api/vendor/list'
                  per_page:
                    type: integer
                    example: 40
                  prev_page_url:
                    type: string
                    example: 'http://localhost/api/vendor/list?page=38'
                  to:
                    type: string
                    example: null
                  total:
                    type: integer
                    example: 0
      tags:
        - Endpoints
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                page:
                  type: integer
                  description: 'Must be at least 0.'
                  example: 39
                per_page:
                  type: integer
                  description: 'Must be at least 0.'
                  example: 40
      security: []
  '/api/vendor/search/{name}':
    get:
      summary: ''
      operationId: getApiVendorSearchName
      description: ''
      parameters: []
      responses:
        422:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'No match found'
                properties:
                  message:
                    type: string
                    example: 'No match found'
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: name
        description: ''
        example: iure
        required: true
        schema:
          type: string
  '/api/vendor/{id}':
    get:
      summary: ''
      operationId: getApiVendorId
      description: ''
      parameters: []
      responses:
        422:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Vendor cannot be found'
                properties:
                  message:
                    type: string
                    example: 'Vendor cannot be found'
      tags:
        - Endpoints
      security: []
    delete:
      summary: ''
      operationId: deleteApiVendorId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the vendor.'
        example: 9
        required: true
        schema:
          type: integer
  /api/category/list:
    get:
      summary: ''
      operationId: getApiCategoryList
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                example: []
      tags:
        - Endpoints
      security: []
  '/api/category/products/{category_slug}':
    get:
      summary: ''
      operationId: getApiCategoryProductsCategory_slug
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Category does not exist'
                properties:
                  message:
                    type: string
                    example: 'Category does not exist'
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: category_slug
        description: 'The slug of the category.'
        example: quas
        required: true
        schema:
          type: string
  /api/product/list:
    get:
      summary: ''
      operationId: getApiProductList
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  current_page: 65
                  data: []
                  first_page_url: 'http://localhost/api/product/list?page=1'
                  from: null
                  last_page: 1
                  last_page_url: 'http://localhost/api/product/list?page=1'
                  links:
                    -
                      url: 'http://localhost/api/product/list?page=64'
                      label: '&laquo; Previous'
                      active: false
                    -
                      url: 'http://localhost/api/product/list?page=1'
                      label: '1'
                      active: false
                    -
                      url: null
                      label: 'Next &raquo;'
                      active: false
                  next_page_url: null
                  path: 'http://localhost/api/product/list'
                  per_page: 84
                  prev_page_url: 'http://localhost/api/product/list?page=64'
                  to: null
                  total: 0
                properties:
                  current_page:
                    type: integer
                    example: 65
                  data:
                    type: array
                    example: []
                  first_page_url:
                    type: string
                    example: 'http://localhost/api/product/list?page=1'
                  from:
                    type: string
                    example: null
                  last_page:
                    type: integer
                    example: 1
                  last_page_url:
                    type: string
                    example: 'http://localhost/api/product/list?page=1'
                  links:
                    type: array
                    example:
                      -
                        url: 'http://localhost/api/product/list?page=64'
                        label: '&laquo; Previous'
                        active: false
                      -
                        url: 'http://localhost/api/product/list?page=1'
                        label: '1'
                        active: false
                      -
                        url: null
                        label: 'Next &raquo;'
                        active: false
                    items:
                      type: object
                      properties:
                        url:
                          type: string
                          example: 'http://localhost/api/product/list?page=64'
                        label:
                          type: string
                          example: '&laquo; Previous'
                        active:
                          type: boolean
                          example: false
                  next_page_url:
                    type: string
                    example: null
                  path:
                    type: string
                    example: 'http://localhost/api/product/list'
                  per_page:
                    type: integer
                    example: 84
                  prev_page_url:
                    type: string
                    example: 'http://localhost/api/product/list?page=64'
                  to:
                    type: string
                    example: null
                  total:
                    type: integer
                    example: 0
      tags:
        - Endpoints
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                page:
                  type: integer
                  description: 'Must be at least 0.'
                  example: 65
                per_page:
                  type: integer
                  description: 'Must be at least 0.'
                  example: 84
      security: []
  /api/product/add:
    post:
      summary: ''
      operationId: postApiProductAdd
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: lkxcsu
                description:
                  type: string
                  description: ''
                  example: 'Aspernatur ex repellendus voluptatum et.'
                price:
                  type: number
                  description: ''
                  example: 16362232.4018
                flexible_pricing:
                  type: boolean
                  description: ''
                  example: true
                brand:
                  type: string
                  description: ''
                  example: sed
                model:
                  type: string
                  description: ''
                  example: qui
                images:
                  type: array
                  description: 'Must be an image. Must not be greater than 2048 kilobytes.'
                  items:
                    type: string
                    format: binary
                barcode_upc:
                  type: string
                  description: 'image validation. Must be 12 characters.'
                  example: qglmhdcvjkkb
                barcode_eac:
                  type: string
                  description: 'Must be 13 characters.'
                  example: unprhghjqekfw
                product_availability:
                  type: boolean
                  description: ''
                  example: false
                tags:
                  type: object
                  description: ''
                  example: null
                  properties: {  }
                category_id:
                  type: string
                  description: ''
                  example: maiores
              required:
                - title
                - price
                - flexible_pricing
                - product_availability
                - category_id
  '/api/product/{id}':
    delete:
      summary: ''
      operationId: deleteApiProductId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the product.'
        example: 6
        required: true
        schema:
          type: integer
tags:
  -
    name: Endpoints
    description: ''
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: 'You can retrieve your token by visiting your dashboard and clicking <b>Generate API token</b>.'
security:
  -
    default: []
