openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/auth/register:
    post:
      summary: ''
      operationId: postApiAuthRegister
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                  description: 'Must not be greater than 100 characters.'
                  example: uxywoziskbtuc
                middle_name:
                  type: string
                  description: 'Must not be greater than 100 characters.'
                  example: l
                last_name:
                  type: string
                  description: 'Must not be greater than 100 characters.'
                  example: awwqblyg
                email:
                  type: string
                  description: 'Must be a valid email address. Must not be greater than 255 characters.'
                  example: maxwell27@example.com
                password:
                  type: string
                  description: 'Must be at least 8 characters. Must not be greater than 64 characters.'
                  example: '<(bl.9?_+O1vuvnu+OhY'
                picture:
                  type: string
                  format: binary
                  description: 'Must be an image. Must not be greater than 2048 kilobytes.'
              required:
                - first_name
                - middle_name
                - last_name
                - email
                - password
      security: []
  /api/auth/login:
    post:
      summary: ''
      operationId: postApiAuthLogin
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: ''
                  example: abbie.vonrueden@example.org
                password:
                  type: string
                  description: ''
                  example: '-o3eodx{(jJc.H'
              required:
                - email
                - password
      security: []
  /api/auth/logout:
    post:
      summary: ''
      operationId: postApiAuthLogout
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
  /api/vendor/register:
    post:
      summary: ''
      operationId: postApiVendorRegister
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                store_name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: ridpd
                phone_number:
                  type: string
                  description: 'Must not be greater than 15 characters.'
                  example: nojqwqlf
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: erik.hessel@example.com
                logo:
                  type: string
                  format: binary
                  description: 'Must be an image. Must not be greater than 2048 kilobytes.'
                zone:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: cdeheigilzkiaobrpwoaira
                region:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: typapthmmtadqpkhgcjgc
                google_map_location:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: i
                website:
                  type: string
                  description: 'Must be a valid URL. Must not be greater than 255 characters.'
                  example: eymvopcgowvuzlrgsbzg
                telegram:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: wzkguvngqrxavzuub
                whatsapp:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: ay
                tin_number:
                  type: string
                  description: 'Must be 10 characters.'
                  example: zhxawmkjki
                license:
                  type: string
                  format: binary
                  description: 'Must be a file. Must not be greater than 2048 kilobytes.'
                description:
                  type: string
                  description: 'Must not be greater than 1000 characters.'
                  example: 'Nisi et eveniet exercitationem qui non.'
              required:
                - store_name
                - phone_number
                - email
                - zone
                - region
                - tin_number
                - license
  /api/vendor/list:
    get:
      summary: ''
      operationId: getApiVendorList
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  current_page: 46
                  data: []
                  first_page_url: 'http://localhost/api/vendor/list?page=1'
                  from: null
                  last_page: 1
                  last_page_url: 'http://localhost/api/vendor/list?page=1'
                  links:
                    -
                      url: 'http://localhost/api/vendor/list?page=45'
                      label: '&laquo; Previous'
                      active: false
                    -
                      url: 'http://localhost/api/vendor/list?page=1'
                      label: '1'
                      active: false
                    -
                      url: null
                      label: 'Next &raquo;'
                      active: false
                  next_page_url: null
                  path: 'http://localhost/api/vendor/list'
                  per_page: 1
                  prev_page_url: 'http://localhost/api/vendor/list?page=45'
                  to: null
                  total: 0
                properties:
                  current_page:
                    type: integer
                    example: 46
                  data:
                    type: array
                    example: []
                  first_page_url:
                    type: string
                    example: 'http://localhost/api/vendor/list?page=1'
                  from:
                    type: string
                    example: null
                  last_page:
                    type: integer
                    example: 1
                  last_page_url:
                    type: string
                    example: 'http://localhost/api/vendor/list?page=1'
                  links:
                    type: array
                    example:
                      -
                        url: 'http://localhost/api/vendor/list?page=45'
                        label: '&laquo; Previous'
                        active: false
                      -
                        url: 'http://localhost/api/vendor/list?page=1'
                        label: '1'
                        active: false
                      -
                        url: null
                        label: 'Next &raquo;'
                        active: false
                    items:
                      type: object
                      properties:
                        url:
                          type: string
                          example: 'http://localhost/api/vendor/list?page=45'
                        label:
                          type: string
                          example: '&laquo; Previous'
                        active:
                          type: boolean
                          example: false
                  next_page_url:
                    type: string
                    example: null
                  path:
                    type: string
                    example: 'http://localhost/api/vendor/list'
                  per_page:
                    type: integer
                    example: 1
                  prev_page_url:
                    type: string
                    example: 'http://localhost/api/vendor/list?page=45'
                  to:
                    type: string
                    example: null
                  total:
                    type: integer
                    example: 0
      tags:
        - Endpoints
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                page:
                  type: integer
                  description: 'Must be at least 0.'
                  example: 46
                per_page:
                  type: integer
                  description: 'Must be at least 0.'
                  example: 1
      security: []
  '/api/vendor/search/{name}':
    get:
      summary: ''
      operationId: getApiVendorSearchName
      description: ''
      parameters: []
      responses:
        422:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'No match found'
                properties:
                  message:
                    type: string
                    example: 'No match found'
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: name
        description: ''
        example: ut
        required: true
        schema:
          type: string
  '/api/vendor/{id}':
    get:
      summary: ''
      operationId: getApiVendorId
      description: ''
      parameters: []
      responses:
        422:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Vendor cannot be found'
                properties:
                  message:
                    type: string
                    example: 'Vendor cannot be found'
      tags:
        - Endpoints
      security: []
    delete:
      summary: ''
      operationId: deleteApiVendorId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the vendor.'
        example: 20
        required: true
        schema:
          type: integer
  /api/category/list:
    get:
      summary: ''
      operationId: getApiCategoryList
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                example: []
      tags:
        - Endpoints
      security: []
tags:
  -
    name: Endpoints
    description: ''
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: 'You can retrieve your token by visiting your dashboard and clicking <b>Generate API token</b>.'
security:
  -
    default: []
