openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/auth/register:
    post:
      summary: ''
      operationId: postApiAuthRegister
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                  description: 'Must not be greater than 100 characters.'
                  example: xpuy
                middle_name:
                  type: string
                  description: 'Must not be greater than 100 characters.'
                  example: wjswgovbjiunqkvgsncakn
                last_name:
                  type: string
                  description: 'Must not be greater than 100 characters.'
                  example: klakk
                email:
                  type: string
                  description: 'Must be a valid email address. Must not be greater than 255 characters.'
                  example: ofelia61@example.net
                password:
                  type: string
                  description: 'Must be at least 8 characters. Must not be greater than 64 characters.'
                  example: 'g("i$Cj1vM+'
                picture:
                  type: string
                  format: binary
                  description: 'Must be an image. Must not be greater than 2048 kilobytes.'
              required:
                - first_name
                - middle_name
                - last_name
                - email
                - password
      security: []
  /api/auth/login:
    post:
      summary: ''
      operationId: postApiAuthLogin
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: ''
                  example: ryder.zboncak@example.net
                password:
                  type: string
                  description: ''
                  example: )w>rzX
              required:
                - email
                - password
      security: []
  /api/auth/logout:
    post:
      summary: ''
      operationId: postApiAuthLogout
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
  /api/vendor/register:
    post:
      summary: ''
      operationId: postApiVendorRegister
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                store_name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: e
                phone_number:
                  type: string
                  description: 'Must not be greater than 15 characters.'
                  example: pzfqeyjafss
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: bud26@example.com
                logo:
                  type: string
                  format: binary
                  description: 'Must be an image. Must not be greater than 2048 kilobytes.'
                zone:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: wbnlpvhwecwsgpfykkara
                region:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: mtpieleevuogwtgfwfyxk
                google_map_location:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: d
                website:
                  type: string
                  description: 'Must be a valid URL. Must not be greater than 255 characters.'
                  example: iginktsfgkfxbksytqrul
                telegram:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: jukjjgnwmfzyakzjcmcxa
                whatsapp:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: dvakiasxck
                tin_number:
                  type: string
                  description: 'Must be 10 characters.'
                  example: nngcfovnjj
                license:
                  type: string
                  format: binary
                  description: 'Must be a file. Must not be greater than 2048 kilobytes.'
                description:
                  type: string
                  description: 'Must not be greater than 1000 characters.'
                  example: 'Iste temporibus sunt eos.'
              required:
                - store_name
                - phone_number
                - email
                - zone
                - region
                - tin_number
                - license
  /api/vendor/list:
    get:
      summary: ''
      operationId: getApiVendorList
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                example: []
      tags:
        - Endpoints
      security: []
  '/api/vendor/search/{name}':
    get:
      summary: ''
      operationId: getApiVendorSearchName
      description: ''
      parameters: []
      responses:
        422:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'No match found'
                properties:
                  message:
                    type: string
                    example: 'No match found'
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: name
        description: ''
        example: assumenda
        required: true
        schema:
          type: string
  '/api/vendor/{id}':
    get:
      summary: ''
      operationId: getApiVendorId
      description: ''
      parameters: []
      responses:
        422:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Vendor cannot be found'
                properties:
                  message:
                    type: string
                    example: 'Vendor cannot be found'
      tags:
        - Endpoints
      security: []
    delete:
      summary: ''
      operationId: deleteApiVendorId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the vendor.'
        example: 14
        required: true
        schema:
          type: integer
  /api/category/list:
    get:
      summary: ''
      operationId: getApiCategoryList
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                example: []
      tags:
        - Endpoints
      security: []
  '/api/category/products/{category_slug}':
    get:
      summary: ''
      operationId: getApiCategoryProductsCategory_slug
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Category does not exist'
                properties:
                  message:
                    type: string
                    example: 'Category does not exist'
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: category_slug
        description: 'The slug of the category.'
        example: cupiditate
        required: true
        schema:
          type: string
  /api/product/list:
    get:
      summary: ''
      operationId: getApiProductList
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                example: []
      tags:
        - Endpoints
      security: []
  /api/product/add:
    post:
      summary: ''
      operationId: postApiProductAdd
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: lpsuux
                description:
                  type: string
                  description: ''
                  example: 'Facere qui id quo voluptatem error vel in.'
                price:
                  type: number
                  description: ''
                  example: 781984949.1
                flexible_pricing:
                  type: boolean
                  description: ''
                  example: true
                brand:
                  type: string
                  description: ''
                  example: sint
                model:
                  type: string
                  description: ''
                  example: repellat
                images:
                  type: array
                  description: 'Must be an image. Must not be greater than 2048 kilobytes.'
                  items:
                    type: string
                    format: binary
                barcode_upc:
                  type: string
                  description: 'image validation. Must be 12 characters.'
                  example: rghxzivawshd
                barcode_eac:
                  type: string
                  description: 'Must be 13 characters.'
                  example: fwjlylzalgphi
                remaining_stock:
                  type: integer
                  description: 'Must be at least 0.'
                  example: 69
                tags:
                  type: object
                  description: ''
                  example: null
                  properties: {  }
                category_id:
                  type: string
                  description: ''
                  example: cum
              required:
                - title
                - price
                - flexible_pricing
                - remaining_stock
                - category_id
  '/api/product/{id}':
    delete:
      summary: ''
      operationId: deleteApiProductId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the product.'
        example: 9
        required: true
        schema:
          type: integer
tags:
  -
    name: Endpoints
    description: ''
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: 'You can retrieve your token by visiting your dashboard and clicking <b>Generate API token</b>.'
security:
  -
    default: []
