openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/auth/register:
    post:
      summary: ''
      operationId: postApiAuthRegister
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                  description: 'Must not be greater than 100 characters.'
                  example: wqpftka
                middle_name:
                  type: string
                  description: 'Must not be greater than 100 characters.'
                  example: zpcnzogpddkp
                last_name:
                  type: string
                  description: 'Must not be greater than 100 characters.'
                  example: rrvzbjlowpwtubgp
                email:
                  type: string
                  description: 'Must be a valid email address. Must not be greater than 255 characters.'
                  example: alta.bechtelar@example.com
                password:
                  type: string
                  description: 'Must be at least 8 characters. Must not be greater than 64 characters.'
                  example: 'y[jEWsN2k['
                picture:
                  type: string
                  format: binary
                  description: 'Must be an image. Must not be greater than 2048 kilobytes.'
              required:
                - first_name
                - middle_name
                - last_name
                - email
                - password
      security: []
  /api/auth/login:
    post:
      summary: ''
      operationId: postApiAuthLogin
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: ''
                  example: ullrich.ben@example.net
                password:
                  type: string
                  description: ''
                  example: 'qDh}2y9g-nTdLIvk'
              required:
                - email
                - password
      security: []
  /api/auth/logout:
    post:
      summary: ''
      operationId: postApiAuthLogout
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
  /api/vendor/register:
    post:
      summary: ''
      operationId: postApiVendorRegister
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                store_name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: zz
                phone_number:
                  type: string
                  description: 'Must not be greater than 15 characters.'
                  example: ekwszvi
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: burnice30@example.net
                logo:
                  type: string
                  format: binary
                  description: 'Must be an image. Must not be greater than 2048 kilobytes.'
                zone:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: vjb
                region:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: weddqwvlansxmtzraung
                google_map_location:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: fstlkly
                website:
                  type: string
                  description: 'Must be a valid URL. Must not be greater than 255 characters.'
                  example: wtgyenjhjmgxl
                telegram:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: bjrszcflhjrkllekqdhroiv
                whatsapp:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: itdukppmhl
                tin_number:
                  type: string
                  description: 'Must be 10 characters.'
                  example: hqzknwlqgs
                license:
                  type: string
                  format: binary
                  description: 'Must be a file. Must not be greater than 2048 kilobytes.'
                description:
                  type: string
                  description: 'Must not be greater than 1000 characters.'
                  example: 'Praesentium accusantium nisi perspiciatis consequatur quia.'
              required:
                - store_name
                - phone_number
                - zone
                - region
                - tin_number
                - license
  /api/vendor/register/bylicense:
    post:
      summary: ''
      operationId: postApiVendorRegisterBylicense
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                license_number:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: kqsoejnivbjqjrxsat
                logo:
                  type: string
                  format: binary
                  description: 'Must be an image. Must not be greater than 2048 kilobytes.'
                license:
                  type: string
                  format: binary
                  description: 'Must be a file. Must not be greater than 2048 kilobytes.'
              required:
                - license_number
                - license
  /api/vendor/list:
    get:
      summary: ''
      operationId: getApiVendorList
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                example: []
      tags:
        - Endpoints
      security: []
  '/api/vendor/search/{name}':
    get:
      summary: ''
      operationId: getApiVendorSearchName
      description: ''
      parameters: []
      responses:
        422:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'No match found'
                properties:
                  message:
                    type: string
                    example: 'No match found'
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: name
        description: ''
        example: quia
        required: true
        schema:
          type: string
  /api/vendor/products:
    get:
      summary: ''
      operationId: getApiVendorProducts
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
  /api/vendor/orders:
    get:
      summary: ''
      operationId: getApiVendorOrders
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
  '/api/vendor/{id}':
    get:
      summary: ''
      operationId: getApiVendorId
      description: ''
      parameters: []
      responses:
        422:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Vendor cannot be found'
                properties:
                  message:
                    type: string
                    example: 'Vendor cannot be found'
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the vendor.'
        example: 6
        required: true
        schema:
          type: integer
  /api/vendor:
    delete:
      summary: ''
      operationId: deleteApiVendor
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
  /api/category/list:
    get:
      summary: ''
      operationId: getApiCategoryList
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                example: []
      tags:
        - Endpoints
      security: []
  '/api/category/products/{category_slug}':
    get:
      summary: ''
      operationId: getApiCategoryProductsCategory_slug
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Category does not exist'
                properties:
                  message:
                    type: string
                    example: 'Category does not exist'
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: category_slug
        description: 'The slug of the category.'
        example: sit
        required: true
        schema:
          type: string
  /api/product/search:
    get:
      summary: ''
      operationId: getApiProductSearch
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                example: []
      tags:
        - Endpoints
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                barcode:
                  type: string
                  description: 'Must be at least 5 characters. Must not be greater than 15 characters.'
                  example: bffoh
                query:
                  type: string
                  description: 'Must be at least 1 character.'
                  example: vjiwbyvedsevubrozssfexlojmuuwtfgvisausadtqmmvjglz
                min:
                  type: number
                  description: 'Must be at least 0.'
                  example: 57
                max:
                  type: number
                  description: 'Must be at least 0.'
                  example: 53
      security: []
  /api/product/list:
    get:
      summary: ''
      operationId: getApiProductList
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                example: []
      tags:
        - Endpoints
      security: []
  /api/product/add:
    post:
      summary: ''
      operationId: postApiProductAdd
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: sfkmmofyvieaqxkuo
                description:
                  type: string
                  description: ''
                  example: 'Deserunt fuga in magnam ad iusto asperiores.'
                price:
                  type: number
                  description: ''
                  example: 556747.3153807
                flexible_pricing:
                  type: boolean
                  description: ''
                  example: true
                brand:
                  type: string
                  description: ''
                  example: perspiciatis
                model:
                  type: string
                  description: ''
                  example: in
                images:
                  type: array
                  description: 'Must be an image. Must not be greater than 2048 kilobytes.'
                  items:
                    type: string
                    format: binary
                barcode_upc:
                  type: string
                  description: 'image validation. Must be 12 characters.'
                  example: ggdilcatomgl
                barcode_eac:
                  type: string
                  description: 'Must be 13 characters.'
                  example: jmtiptrkzbsnk
                remaining_stock:
                  type: integer
                  description: 'Must be at least 0.'
                  example: 37
                tags:
                  type: object
                  description: ''
                  example: null
                  properties: {  }
                category_id:
                  type: string
                  description: ''
                  example: corrupti
              required:
                - title
                - price
                - flexible_pricing
                - remaining_stock
                - category_id
  '/api/product/{id}':
    get:
      summary: ''
      operationId: getApiProductId
      description: ''
      parameters: []
      responses:
        422:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Product cannot be found'
                properties:
                  message:
                    type: string
                    example: 'Product cannot be found'
      tags:
        - Endpoints
      security: []
    delete:
      summary: ''
      operationId: deleteApiProductId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the product.'
        example: 7
        required: true
        schema:
          type: integer
  /api/user/orders:
    get:
      summary: ''
      operationId: getApiUserOrders
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
  /api/orders/add:
    get:
      summary: ''
      operationId: getApiOrdersAdd
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                product_id:
                  type: string
                  description: ''
                  example: ducimus
              required:
                - product_id
tags:
  -
    name: Endpoints
    description: ''
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: 'You can retrieve your token by visiting your dashboard and clicking <b>Generate API token</b>.'
security:
  -
    default: []
