openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/auth/register:
    post:
      summary: ''
      operationId: postApiAuthRegister
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                  description: 'Must not be greater than 100 characters.'
                  example: jpvwmnedazpshowbzojzuhd
                  nullable: false
                middle_name:
                  type: string
                  description: 'Must not be greater than 100 characters.'
                  example: fiqnfexzdtzxj
                  nullable: false
                last_name:
                  type: string
                  description: 'Must not be greater than 100 characters.'
                  example: wml
                  nullable: false
                email:
                  type: string
                  description: 'Must be a valid email address. Must not be greater than 255 characters.'
                  example: pfranecki@example.org
                  nullable: false
                password:
                  type: string
                  description: 'Must be at least 8 characters. Must not be greater than 64 characters.'
                  example: '0qe+s==9@,Y'
                  nullable: false
                picture:
                  type: string
                  format: binary
                  description: 'Must be an image. Must not be greater than 2048 kilobytes.'
                  nullable: true
              required:
                - first_name
                - middle_name
                - last_name
                - email
                - password
      security: []
  /api/auth/login:
    post:
      summary: ''
      operationId: postApiAuthLogin
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: ''
                  example: retha34@example.org
                  nullable: false
                password:
                  type: string
                  description: ''
                  example: '46PY:{~C'
                  nullable: false
              required:
                - email
                - password
      security: []
  /api/auth/logout:
    post:
      summary: ''
      operationId: postApiAuthLogout
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
  /api/vendor/register:
    post:
      summary: ''
      operationId: postApiVendorRegister
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                store_name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: oeoljnfogplwhbyyv
                  nullable: false
                phone_number:
                  type: string
                  description: 'Must not be greater than 15 characters.'
                  example: ji
                  nullable: false
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: louvenia83@example.org
                  nullable: false
                logo:
                  type: string
                  format: binary
                  description: 'Must be an image. Must not be greater than 2048 kilobytes.'
                  nullable: true
                zone:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: rvdxflswjlwcab
                  nullable: false
                region:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: izkxt
                  nullable: false
                google_map_location:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: plaxcmvkadzdp
                  nullable: true
                website:
                  type: string
                  description: 'Must be a valid URL. Must not be greater than 255 characters.'
                  example: qundapnrczn
                  nullable: true
                telegram:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: dgbgllmcn
                  nullable: true
                whatsapp:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: ujgdwdw
                  nullable: true
                tin_number:
                  type: string
                  description: 'Must be 10 characters.'
                  example: crfpwmyvuj
                  nullable: false
                license:
                  type: string
                  format: binary
                  description: 'Must be a file. Must not be greater than 2048 kilobytes.'
                  nullable: false
                description:
                  type: string
                  description: 'Must not be greater than 1000 characters.'
                  example: 'Dolorem rerum aut quam ex.'
                  nullable: true
              required:
                - store_name
                - phone_number
                - zone
                - region
                - tin_number
                - license
  /api/vendor/register/bylicense:
    post:
      summary: ''
      operationId: postApiVendorRegisterBylicense
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                license_number:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: jc
                  nullable: false
                logo:
                  type: string
                  format: binary
                  description: 'Must be an image. Must not be greater than 2048 kilobytes.'
                  nullable: true
                license:
                  type: string
                  format: binary
                  description: 'Must be a file. Must not be greater than 2048 kilobytes.'
                  nullable: false
              required:
                - license_number
                - license
  /api/vendor/list:
    get:
      summary: ''
      operationId: getApiVendorList
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                example: []
      tags:
        - Endpoints
      security: []
  '/api/vendor/search/{name}':
    get:
      summary: ''
      operationId: getApiVendorSearchName
      description: ''
      parameters: []
      responses:
        422:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'No match found'
                properties:
                  message:
                    type: string
                    example: 'No match found'
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: name
        description: ''
        example: non
        required: true
        schema:
          type: string
  /api/vendor/products:
    get:
      summary: ''
      operationId: getApiVendorProducts
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
  /api/vendor/orders:
    get:
      summary: ''
      operationId: getApiVendorOrders
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
  '/api/vendor/{id}':
    get:
      summary: ''
      operationId: getApiVendorId
      description: ''
      parameters: []
      responses:
        422:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Vendor cannot be found'
                properties:
                  message:
                    type: string
                    example: 'Vendor cannot be found'
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the vendor.'
        example: 10
        required: true
        schema:
          type: integer
  /api/vendor:
    delete:
      summary: ''
      operationId: deleteApiVendor
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
  /api/category/list:
    get:
      summary: ''
      operationId: getApiCategoryList
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                example: []
      tags:
        - Endpoints
      security: []
  '/api/category/products/{category_slug}':
    get:
      summary: ''
      operationId: getApiCategoryProductsCategory_slug
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Category does not exist'
                properties:
                  message:
                    type: string
                    example: 'Category does not exist'
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: category_slug
        description: 'The slug of the category.'
        example: dolorem
        required: true
        schema:
          type: string
  /api/product/search:
    get:
      summary: ''
      operationId: getApiProductSearch
      description: ''
      parameters: []
      responses:
        422:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Validation failed'
                  errors:
                    barcode:
                      - 'The barcode field must be at least 5 characters.'
                properties:
                  message:
                    type: string
                    example: 'Validation failed'
                  errors:
                    type: object
                    properties:
                      barcode:
                        type: array
                        example:
                          - 'The barcode field must be at least 5 characters.'
                        items:
                          type: string
      tags:
        - Endpoints
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                barcode:
                  type: string
                  description: 'Must be at least 5 characters. Must not be greater than 15 characters.'
                  example: tp
                  nullable: true
                query:
                  type: string
                  description: 'Must be at least 1 character.'
                  example: qsutlidumksisnlbpeqsexadymzlprrdtjai
                  nullable: true
                min:
                  type: number
                  description: 'Must be at least 0.'
                  example: 27
                  nullable: true
                max:
                  type: number
                  description: 'Must be at least 0.'
                  example: 0
                  nullable: true
      security: []
  /api/product/list:
    get:
      summary: ''
      operationId: getApiProductList
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                example: []
      tags:
        - Endpoints
      security: []
  /api/product/add:
    post:
      summary: ''
      operationId: postApiProductAdd
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: fu
                  nullable: false
                description:
                  type: string
                  description: ''
                  example: 'Et optio sapiente et voluptatibus molestiae voluptatem.'
                  nullable: true
                price:
                  type: number
                  description: ''
                  example: 215292.3165239
                  nullable: false
                flexible_pricing:
                  type: boolean
                  description: ''
                  example: false
                  nullable: false
                brand:
                  type: string
                  description: ''
                  example: tenetur
                  nullable: true
                model:
                  type: string
                  description: ''
                  example: voluptatem
                  nullable: true
                images:
                  type: array
                  description: 'Must be an image. Must not be greater than 2048 kilobytes.'
                  items:
                    type: string
                    format: binary
                barcode_upc:
                  type: string
                  description: 'image validation. Must be 12 characters.'
                  example: eeferzvmfirv
                  nullable: true
                barcode_eac:
                  type: string
                  description: 'Must be 13 characters.'
                  example: wbbirpyrmfguj
                  nullable: true
                remaining_stock:
                  type: integer
                  description: 'Must be at least 0.'
                  example: 66
                  nullable: false
                tags:
                  type: object
                  description: ''
                  example: null
                  nullable: true
                  properties: {  }
                category_id:
                  type: string
                  description: 'The <code>id</code> of an existing record in the categories table.'
                  example: pariatur
                  nullable: false
              required:
                - title
                - price
                - flexible_pricing
                - remaining_stock
                - category_id
  '/api/product/{id}':
    get:
      summary: ''
      operationId: getApiProductId
      description: ''
      parameters: []
      responses:
        422:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Product cannot be found'
                properties:
                  message:
                    type: string
                    example: 'Product cannot be found'
      tags:
        - Endpoints
      security: []
    delete:
      summary: ''
      operationId: deleteApiProductId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the product.'
        example: 10
        required: true
        schema:
          type: integer
  /api/user/orders:
    get:
      summary: ''
      operationId: getApiUserOrders
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
  /api/orders/add:
    get:
      summary: ''
      operationId: getApiOrdersAdd
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                product_id:
                  type: string
                  description: 'The <code>id</code> of an existing record in the products table.'
                  example: reiciendis
                  nullable: false
              required:
                - product_id
tags:
  -
    name: Endpoints
    description: ''
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: 'You can retrieve your token by visiting your dashboard and clicking <b>Generate API token</b>.'
security:
  -
    default: []
