openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/auth/register:
    post:
      summary: ''
      operationId: postApiAuthRegister
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                  description: 'Must not be greater than 100 characters.'
                  example: ydqfltwzqjukwzk
                middle_name:
                  type: string
                  description: 'Must not be greater than 100 characters.'
                  example: axixhhlixmnsxtlhfwkos
                last_name:
                  type: string
                  description: 'Must not be greater than 100 characters.'
                  example: pewkupmiagcertotywuhoo
                email:
                  type: string
                  description: 'Must be a valid email address. Must not be greater than 255 characters.'
                  example: abraham.lehner@example.com
                password:
                  type: string
                  description: 'Must be at least 8 characters. Must not be greater than 64 characters.'
                  example: "g1!'@.{doiR_WLV?*.8m"
                picture:
                  type: string
                  format: binary
                  description: 'Must be an image. Must not be greater than 2048 kilobytes.'
              required:
                - first_name
                - middle_name
                - last_name
                - email
                - password
      security: []
  /api/auth/login:
    post:
      summary: ''
      operationId: postApiAuthLogin
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: ''
                  example: uchamplin@example.org
                password:
                  type: string
                  description: ''
                  example: 'o5x[8jFI[e1\.H'
              required:
                - email
                - password
      security: []
  /api/auth/logout:
    post:
      summary: ''
      operationId: postApiAuthLogout
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
  /api/vendor/register:
    post:
      summary: ''
      operationId: postApiVendorRegister
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                store_name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: kcohboetqdcrexvgylvbnmoe
                phone_number:
                  type: string
                  description: 'Must not be greater than 15 characters.'
                  example: sk
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: tking@example.org
                logo:
                  type: string
                  format: binary
                  description: 'Must be an image. Must not be greater than 2048 kilobytes.'
                zone:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: mywjpbuugwploxxkp
                region:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: yfec
                google_map_location:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: njukzwrqwxsko
                website:
                  type: string
                  description: 'Must be a valid URL. Must not be greater than 255 characters.'
                  example: pcrywnqrrnlrvvlmiychstqn
                telegram:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: hbyye
                whatsapp:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: exhobaaytsqwttfogpr
                tin_number:
                  type: string
                  description: 'Must not be greater than 20 characters.'
                  example: ctc
                license:
                  type: string
                  format: binary
                  description: 'Must be a file. Must not be greater than 2048 kilobytes.'
                description:
                  type: string
                  description: 'Must not be greater than 1000 characters.'
                  example: 'Adipisci quam eos accusantium eligendi.'
              required:
                - store_name
                - phone_number
                - email
                - zone
                - region
                - tin_number
                - license
      security: []
tags:
  -
    name: Endpoints
    description: ''
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: 'You can retrieve your token by visiting your dashboard and clicking <b>Generate API token</b>.'
security:
  -
    default: []
