openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/auth/register:
    post:
      summary: ''
      operationId: postApiAuthRegister
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                  description: 'Must not be greater than 100 characters.'
                  example: ctflteqr
                middle_name:
                  type: string
                  description: 'Must not be greater than 100 characters.'
                  example: guceffijfl
                last_name:
                  type: string
                  description: 'Must not be greater than 100 characters.'
                  example: ykgmdwwytmxwvoa
                email:
                  type: string
                  description: 'Must be a valid email address. Must not be greater than 255 characters.'
                  example: destin95@example.com
                password:
                  type: string
                  description: 'Must be at least 8 characters. Must not be greater than 64 characters.'
                  example: '~{vDB,"^aU'
                picture:
                  type: string
                  format: binary
                  description: 'Must be an image. Must not be greater than 2048 kilobytes.'
              required:
                - first_name
                - middle_name
                - last_name
                - email
                - password
      security: []
  /api/auth/login:
    post:
      summary: ''
      operationId: postApiAuthLogin
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: ''
                  example: aleuschke@example.org
                password:
                  type: string
                  description: ''
                  example: 7alO$viZR
              required:
                - email
                - password
      security: []
  /api/auth/logout:
    post:
      summary: ''
      operationId: postApiAuthLogout
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
  /api/vendor/register:
    post:
      summary: ''
      operationId: postApiVendorRegister
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                store_name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: ezok
                phone_number:
                  type: string
                  description: 'Must not be greater than 15 characters.'
                  example: z
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: jarrett.reynolds@example.com
                logo:
                  type: string
                  format: binary
                  description: 'Must be an image. Must not be greater than 2048 kilobytes.'
                zone:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: lormdupmphmsswrclixpunzu
                region:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: ravbw
                google_map_location:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: xsrgvrlxgcja
                website:
                  type: string
                  description: 'Must be a valid URL. Must not be greater than 255 characters.'
                  example: osgebcethheuhvhjsmyvt
                telegram:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: nevumqlrfrvhilbwlkwloyr
                whatsapp:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: fufbsrwwguzsjhdl
                tin_number:
                  type: string
                  description: 'Must be 10 characters.'
                  example: vttodsaplk
                license:
                  type: string
                  format: binary
                  description: 'Must be a file. Must not be greater than 2048 kilobytes.'
                description:
                  type: string
                  description: 'Must not be greater than 1000 characters.'
                  example: 'Et et quia ipsam.'
              required:
                - store_name
                - phone_number
                - email
                - zone
                - region
                - tin_number
                - license
  /api/vendor/list:
    get:
      summary: ''
      operationId: getApiVendorList
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  current_page: 67
                  data: []
                  first_page_url: 'http://localhost/api/vendor/list?page=1'
                  from: null
                  last_page: 1
                  last_page_url: 'http://localhost/api/vendor/list?page=1'
                  links:
                    -
                      url: 'http://localhost/api/vendor/list?page=66'
                      label: '&laquo; Previous'
                      active: false
                    -
                      url: 'http://localhost/api/vendor/list?page=1'
                      label: '1'
                      active: false
                    -
                      url: null
                      label: 'Next &raquo;'
                      active: false
                  next_page_url: null
                  path: 'http://localhost/api/vendor/list'
                  per_page: 33
                  prev_page_url: 'http://localhost/api/vendor/list?page=66'
                  to: null
                  total: 0
                properties:
                  current_page:
                    type: integer
                    example: 67
                  data:
                    type: array
                    example: []
                  first_page_url:
                    type: string
                    example: 'http://localhost/api/vendor/list?page=1'
                  from:
                    type: string
                    example: null
                  last_page:
                    type: integer
                    example: 1
                  last_page_url:
                    type: string
                    example: 'http://localhost/api/vendor/list?page=1'
                  links:
                    type: array
                    example:
                      -
                        url: 'http://localhost/api/vendor/list?page=66'
                        label: '&laquo; Previous'
                        active: false
                      -
                        url: 'http://localhost/api/vendor/list?page=1'
                        label: '1'
                        active: false
                      -
                        url: null
                        label: 'Next &raquo;'
                        active: false
                    items:
                      type: object
                      properties:
                        url:
                          type: string
                          example: 'http://localhost/api/vendor/list?page=66'
                        label:
                          type: string
                          example: '&laquo; Previous'
                        active:
                          type: boolean
                          example: false
                  next_page_url:
                    type: string
                    example: null
                  path:
                    type: string
                    example: 'http://localhost/api/vendor/list'
                  per_page:
                    type: integer
                    example: 33
                  prev_page_url:
                    type: string
                    example: 'http://localhost/api/vendor/list?page=66'
                  to:
                    type: string
                    example: null
                  total:
                    type: integer
                    example: 0
      tags:
        - Endpoints
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                page:
                  type: integer
                  description: 'Must be at least 0.'
                  example: 67
                per_page:
                  type: integer
                  description: 'Must be at least 0.'
                  example: 33
      security: []
  '/api/vendor/search/{name}':
    get:
      summary: ''
      operationId: getApiVendorSearchName
      description: ''
      parameters: []
      responses:
        422:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'No match found'
                properties:
                  message:
                    type: string
                    example: 'No match found'
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: name
        description: ''
        example: beatae
        required: true
        schema:
          type: string
  '/api/vendor/{id}':
    get:
      summary: ''
      operationId: getApiVendorId
      description: ''
      parameters: []
      responses:
        422:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Vendor cannot be found'
                properties:
                  message:
                    type: string
                    example: 'Vendor cannot be found'
      tags:
        - Endpoints
      security: []
    delete:
      summary: ''
      operationId: deleteApiVendorId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the vendor.'
        example: 19
        required: true
        schema:
          type: integer
  /api/category/list:
    get:
      summary: ''
      operationId: getApiCategoryList
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                example: []
      tags:
        - Endpoints
      security: []
  '/api/category/products/{category_slug}':
    get:
      summary: ''
      operationId: getApiCategoryProductsCategory_slug
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Category does not exist'
                properties:
                  message:
                    type: string
                    example: 'Category does not exist'
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: category_slug
        description: 'The slug of the category.'
        example: ipsum
        required: true
        schema:
          type: string
  /api/product/list:
    get:
      summary: ''
      operationId: getApiProductList
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  current_page: 14
                  data: []
                  first_page_url: 'http://localhost/api/product/list?page=1'
                  from: null
                  last_page: 1
                  last_page_url: 'http://localhost/api/product/list?page=1'
                  links:
                    -
                      url: 'http://localhost/api/product/list?page=13'
                      label: '&laquo; Previous'
                      active: false
                    -
                      url: 'http://localhost/api/product/list?page=1'
                      label: '1'
                      active: false
                    -
                      url: null
                      label: 'Next &raquo;'
                      active: false
                  next_page_url: null
                  path: 'http://localhost/api/product/list'
                  per_page: 42
                  prev_page_url: 'http://localhost/api/product/list?page=13'
                  to: null
                  total: 0
                properties:
                  current_page:
                    type: integer
                    example: 14
                  data:
                    type: array
                    example: []
                  first_page_url:
                    type: string
                    example: 'http://localhost/api/product/list?page=1'
                  from:
                    type: string
                    example: null
                  last_page:
                    type: integer
                    example: 1
                  last_page_url:
                    type: string
                    example: 'http://localhost/api/product/list?page=1'
                  links:
                    type: array
                    example:
                      -
                        url: 'http://localhost/api/product/list?page=13'
                        label: '&laquo; Previous'
                        active: false
                      -
                        url: 'http://localhost/api/product/list?page=1'
                        label: '1'
                        active: false
                      -
                        url: null
                        label: 'Next &raquo;'
                        active: false
                    items:
                      type: object
                      properties:
                        url:
                          type: string
                          example: 'http://localhost/api/product/list?page=13'
                        label:
                          type: string
                          example: '&laquo; Previous'
                        active:
                          type: boolean
                          example: false
                  next_page_url:
                    type: string
                    example: null
                  path:
                    type: string
                    example: 'http://localhost/api/product/list'
                  per_page:
                    type: integer
                    example: 42
                  prev_page_url:
                    type: string
                    example: 'http://localhost/api/product/list?page=13'
                  to:
                    type: string
                    example: null
                  total:
                    type: integer
                    example: 0
      tags:
        - Endpoints
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                page:
                  type: integer
                  description: 'Must be at least 1.'
                  example: 14
                per_page:
                  type: integer
                  description: 'Must be at least 1.'
                  example: 42
      security: []
  /api/product/add:
    post:
      summary: ''
      operationId: postApiProductAdd
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: fkcndihdafwybfymishmoeiu
                description:
                  type: string
                  description: ''
                  example: 'Architecto autem quis rerum deserunt ad.'
                price:
                  type: number
                  description: ''
                  example: 46335349.9
                flexible_pricing:
                  type: boolean
                  description: ''
                  example: false
                brand:
                  type: string
                  description: ''
                  example: pariatur
                model:
                  type: string
                  description: ''
                  example: quaerat
                images:
                  type: array
                  description: 'Must be an image. Must not be greater than 2048 kilobytes.'
                  items:
                    type: string
                    format: binary
                barcode_upc:
                  type: string
                  description: 'image validation. Must be 12 characters.'
                  example: ategaphwyeoz
                barcode_eac:
                  type: string
                  description: 'Must be 13 characters.'
                  example: nicllxozvqgcc
                remaining_stock:
                  type: integer
                  description: 'Must be at least 0.'
                  example: 79
                tags:
                  type: object
                  description: ''
                  example: null
                  properties: {  }
                category_id:
                  type: string
                  description: ''
                  example: sed
              required:
                - title
                - price
                - flexible_pricing
                - remaining_stock
                - category_id
  '/api/product/{id}':
    delete:
      summary: ''
      operationId: deleteApiProductId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the product.'
        example: 19
        required: true
        schema:
          type: integer
tags:
  -
    name: Endpoints
    description: ''
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: 'You can retrieve your token by visiting your dashboard and clicking <b>Generate API token</b>.'
security:
  -
    default: []
