openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/user/register:
    post:
      summary: ''
      operationId: postApiUserRegister
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                  description: ''
                  example: quidem
                middle_name:
                  type: string
                  description: ''
                  example: quo
                last_name:
                  type: string
                  description: ''
                  example: eligendi
                email:
                  type: string
                  description: ''
                  example: dayna61@example.net
                password:
                  type: string
                  description: ''
                  example: '|Lm#~oH8}#=1<0Z{d'
              required:
                - first_name
                - middle_name
                - last_name
                - email
                - password
      security: []
  /api/user/login:
    post:
      summary: ''
      operationId: postApiUserLogin
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: ''
                  example: maggio.helmer@example.org
                password:
                  type: string
                  description: ''
                  example: PS%nzS
              required:
                - email
                - password
      security: []
  /api/user/logout:
    post:
      summary: ''
      operationId: postApiUserLogout
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
tags:
  -
    name: Endpoints
    description: ''
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: 'You can retrieve your token by visiting your dashboard and clicking <b>Generate API token</b>.'
security:
  -
    default: []
